### ISSUE TITLE
Running history files from google colab

### ISSUE THREAD

**Issue by gpans** [voxcraft/voxcraft-viz#3]
Hi,

I am looking to use voxcraft-viz to design/generate some soft robots and downloaded voxcraft-viz for windows. The example history demos (e.g. m190) works fine no problem. But when I follow the tutorial to create my own in google colab (even just the red block falling) and upload that file, the voxcraft-viz gui freezes says not-responding and never loads (although this should be much lower computation than the example files). 

Any ideas or suggestions would be much appreciated

Thanks
Gaetan

**Comment by gpans** [comment]
Hi,

I got it fixed when installing voxcraft-viz through docker and running the following command  ./voxcraft-sim -i ../demos/basic/ -o output.xml -f >test1.history instead of just /voxcraft-sim -i ../demos/basic/ -o test1.history, it seems that the xml file is needed to sucessfully create the history file

Thanks looking forward to creating some cool simulations

**Comment by liusida** [comment]
Great to hear that you've fixed this. Thanks for using this tool and enjoy!
